[package]
name = "massa_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
async-trait = "0.1.58"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
tower-http = { version = "0.3.4", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
hyper = "0.14.20"
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1"
itertools = "0.10"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
# custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_pool_exports = { path = "../massa-pool-exports" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_pos_exports = { path = "../massa-pos-exports" }
massa_storage = { path = "../massa-storage" }
massa_serialization = { path = "../massa-serialization"}
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_wallet = { path = "../massa-wallet" }